#! /usr/bin/env bash

# assumes to be called from the project root

set -e

build() (
  mkdir -p dist
  mkdir -p dist/data
  cd "frontend"
  elm make src/Main.elm --optimize --output=../dist/elm.js
  cp index.html about.html atlas-info.html logo.svg opensans.ttf *.pdf ../dist/
  cp ../data/ND.csv ../data/aal3_matrix_order.json ../data/aal3_network_mapping.csv ../dist/data/
  sudo apt install nginx -y
)

if [ $# -eq 1 ] && [ "$1" == "watch" ]; then
  while inotifywait -e close_write frontend/src/* frontend/index.html; do
    build
  done
else
  build
fi
